name = "GitLabCodeQualityReports"
uuid = "96e47e59-5107-4718-acc0-ede47ee1aa3b"
authors = ["Daniel Matz <daniel.matz@gmail.com>"]
version = "0.1.0"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
JSON = "0.21.4"
julia = "1.7"
